spring.datasource.url=jdbc:postgresql://dpg-cuhk4u3tq21c73bba7s0-a.virginia-postgres.render.com:5432/db_app_ssjg
spring.datasource.username=admin
spring.datasource.password=LL3fNHMZ9ndpanyIP246m2sjT1mo0PAO
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update