import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/?zx=1773853443022&no_sw_cr=1');
  await page.getByRole('combobox', { name: 'Pesquisar' }).click();
  await page.getByRole('combobox', { name: 'Pesquisar' }).fill('playwr');
  await page.getByRole('combobox', { name: 'Pesquisar' }).press('ArrowDown');
  await page.locator('iframe[name="a-j7c2i9bdpil3"]').contentFrame().getByRole('checkbox', { name: 'Não sou um robô' }).click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().getByRole('button', { name: 'Avançar' }).click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().getByRole('button', { name: 'Verificar' }).click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().getByRole('button', { name: 'Verificar' }).click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-j7c2i9bdpil3"]').contentFrame().getByRole('button', { name: 'Verificar' }).click();
});
